### ISSUE TITLE
Memory leaked after tinyobj_parse_obj do file_reader

### ISSUE THREAD

**Issue by refactor** [syoyo/tinyobjloader-c#45]
buf hold the readed file content, but no place to free it.

**Comment by syoyo** [comment]
You need to show the line

**Comment by nashidau** [comment]
There is no line for the leak.  The problem is in the file reader buf is allocated and passed back in.  But it isn't freed.
I think a better fix is to add a context pointer to the file reader.  Then caller can clean up after.

**Comment by syoyo** [comment]
@nashidau Thanks for the detailed information. App user need to explicitly manage the pointer to `buf`(since there is no `free` when the memory is allocated with mmap). 

At least I need to add freeing pointer code in `example/viewer` example and describe how to manage memory in README.

> I think a better fix is to add a context pointer to the file reader

Yes, this is the best way to fix. I'll do that.

**Comment by nashidau** [comment]
I jus tmade a pull request that adds it.

**Comment by syoyo** [comment]
@nashidau :+1:  

PR https://github.com/syoyo/tinyobjloader-c/pull/46 has been merged so close the issue.
